# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift


name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  print:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print Test
      run: |
        echo "current directory : `pwd`"
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Utility Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDUtilitySDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: Utility Test
      run: |
        cd source/DIDClientSDK
        open -b com.apple.iphonesimulator
        xcodebuild test -scheme DIDUtilitySDKTests -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    
    - name: DataModel Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDDataModelSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: DataModel Test
      run: |
        cd source/DIDClientSDK
        open -b com.apple.iphonesimulator
        xcodebuild test -scheme DIDDataModelSDKTests -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    
    - name: Core Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDCoreSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: Core Test
      run: |
        cd source/DIDClientSDK
        open -b com.apple.iphonesimulator
        xcodebuild test -scheme DIDCoreSDKTests -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
        
    - name: Communication Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDCommunicationSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: Communication Test
      run: |
        cd source/DIDClientSDK
        open -b com.apple.iphonesimulator
        xcodebuild test -scheme DIDCommunicationSDKTests -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

    - name: Wallet Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDWalletSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
    - name: Wallet Test
      run: |
        cd source/DIDClientSDK
        open -b com.apple.iphonesimulator
        xcodebuild test -scheme DIDWalletSDKTests -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
